config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :tasks, only: [:create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  include RailsSortable::Model
  set_sortable :sort
  belongs_to :user

  validates :name, presence: true, length: { in: 4..10  }

  def sortable_id
    "Task_#{self.id}"
  end

end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks

  def sortable_id
    "Task_#{self.id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      @tasks = current_user.tasks.order(:sort)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  def create
    @task = Task.new(name: params[:name], user_id: current_user.id)
    respond_to do |format|
      if @task.save
        format.js
        format.json {render json: @task, layout: false }
      else
        render root_path
      end
    end
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if (@task.update(state: true))
        format.js
        format.json { render json: @task, layout: false }
      end
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/home/_header.html.slim
nav class="navbar navbar-light bg-light"
  = link_to 'Task management system', root_path, class: 'navbar-brand'
  div.form-inline
    - if user_signed_in?
      = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger'
    - else
      = link_to 'Sign in', new_user_session_path, class: 'btn btn-primary'

app/views/home/_list.html.slim
| <li class='list-group-item d-flex justify-content-between align-items-center my-1 list-group-item-dark' id="
= sortable_id
|">
- if task.state
  s
    = task.name
  input type="checkbox" class='pull-right' id="field-id-#{task.id}" disabled="disabled" checked="checked"
- else
  = task.name
  input type="checkbox" class='pull-right' id="field-id-#{task.id}"

app/views/home/index.html.slim
- if !user_signed_in?
  h1 class="text-center" Some content
- else
  h1 class="text-center" My tasks
  div class="container my-5"
    ul.sortable
      - @tasks.each_with_sortable_id do |task, sortable_id|
        = render 'home/list', task: task, sortable_id: sortable_id

    div class="row my-5"
      div.col-md-1
      div class="col-md-9"
        input type="text" class="form-control" id="InputTask"
      div class="col-md-2"
        = link_to 'Add task', tasks_path, method: :post, class: 'btn btn-secondary', id: 'AddButton', remote: true

app/views/layouts/_notification.html.slim
- if !notice.nil?
  = notice
- if !alert.nil?
  = alert

app/views/layouts/application.html.slim
doctype html
html
  head
    title Task management system
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  body
    = render 'home/header'
    = render 'layouts/notification'
    = yield

app/views/tasks/create.js.slim
| $(".sortable").append("#{ j(render 'home/list', task: @task, sortable_id: @task.sortable_id)}")

app/views/tasks/update.js.slim
| $("#Task_#{@task.id}").replaceWith("#{ j(render 'home/list', task: @task, sortable_id: @task.sortable_id)} ");

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br